### ISSUE TITLE
JSON Comments/Suggestions

### ISSUE THREAD

**Issue by jimf99** [pulcher/HugoBot#26]
Congrats Harold.
I saw the updates, send/receive JSON looks straightforward.
You might want to add another key/value pair for speed as well.
Not sure how that would look, but maybe something like this.
{ "dir":"FL","speed":50}
Direction would be Forward Left
Speed would be 50% of maxSpeed
dir values FR = Forward Right, FC=Forward Center, FL=Forward Left
dir values CR = Center Right, CL=Center Left 
dir values BR=Backwards Right,BC=Backwards Center,BL=Backwards Left
dir values RR=Rotate Right, RL=Rotate Left
add the key/value pair of timeMs for duration to do the command.
add the key/value pair of claw for position.
example {"claw":"open","claw":"closed"} or {"claw":0} or {"claw:",100} the 0,100 are percent opened. 100=Full Opened

**Comment by pulcher** [comment]
We are gonna have do something more than this.  I am writing up a retro, so that we can do a lessons learned sorta thing and make plans to make both HugoBot and JimBot better.
