### ISSUE TITLE
Angle Test

### ISSUE THREAD

**Issue by jimf99** [pulcher/HugoBot#4]
![angle_test](https://github.com/pulcher/HugoBot/assets/6600380/40919421-af3e-44c9-a5e0-adf7447ec7fe)

**Comment by jimf99** [comment]
From JimFyyc on Twitch.
Just an example for ArcTan2...
https://www.tinkercad.com/things/85DuE6WgSHx-angle-tests/editel

**Comment by pulcher** [comment]
Thanks Jim!
